map_config:
  map_file: "complex_office.stl"
  map_dimension: 2
  
  # Initial position and orientation of the robot under the world frame
  init_x: 0.0
  init_y: 0.0
  init_z: 0.0
  init_yaw: 0.0

  map_size:
    # Size of the map in meters
    map_min_x: -20.0
    map_min_y: -20.0
    map_min_z: -1.0
    map_max_x: 20.0
    map_max_y: 20.0
    map_max_z: 3.0

    # Size of the task bbox in meters
    # If not set, the whole map will be used
    box_min_x: -15.0
    box_min_y: -15.0
    box_min_z: 0.0
    box_max_x: 15.0
    box_max_y: 15.0
    box_max_z: 2.0

    # Size of the visualization bbox in meters
    # If not set, the whole map will be used
    vbox_min_x: -16.0
    vbox_min_y: -16.0
    vbox_min_z: -0.2
    vbox_max_x: 16.0
    vbox_max_y: 16.0
    vbox_max_z: 2.0
  
  scale: 1.0

  T_b_c:
  - [ 0.0, 0.0, 1.0, 0.0]
  - [-1.0, 0.0, 0.0, 0.0]
  - [ 0.0,-1.0, 0.0, 0.0]
  - [ 0.0, 0.0, 0.0, 1.0]

  T_m_w:
  - [ 0.0,-1.0, 0.0,15.5]
  - [ 0.0, 0.0, 1.0, 0.5]
  - [-1.0, 0.0, 0.0,15.5]
  - [ 0.0, 0.0, 0.0, 1.0]